import type { FishDefinition } from './types';

export const FISH = [
  {
    id: 'river-minnow',
    artwork: '/images/fish_art_a/Lightning Fish Racing Through Mystic Waters.png',
    behavior: 'darting',
    stats: { power: 10, stamina: 12, speed: 34, technique: 9 },
    sizeRangeCm: { min: 4, max: 11 },
    name: { th: 'ปลาซิวสายฟ้า', en: 'Lightning Minnow' },
    description: {
      th: 'ปลาซิวสีทองและน้ำเงินว่ายเป็นฝูง พุ่งวาบเหนือผิวน้ำเมื่อถูกรบกวน',
      en: 'A blue-and-gold minnow that flashes through the shallows in quick, light bursts.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank'],
    tier: 1,
    rarity: 'common',
    habitat: ['shallow-edge', 'open-water'],
    activeTime: ['morning', 'day'],
    preferredBaitIds: ['bread-crumbs', 'shiny-spinner'],
    sellValue: 4,
    rewards: { money: 4, reputation: 1 },
    collection: {
      entry: { th: 'เกล็ดสีฟ้าและทองวาบขึ้นพร้อมกันเมื่อฝูงปลาซิวพุ่งผ่านน้ำตื้น', en: 'Blue-and-gold scales flash together as the school darts through the shallows.' },
      silhouette: 'fish-silhouette-river-minnow',
    },
    weightFactor: 0.08,
    combat: { archetype: 'calm', resistance: 14 },
  },
  {
    id: 'reed-perch',
    artwork: '/images/fish_art_a/Moonlit Duskmist Needlefish Chase.png',
    behavior: 'darting',
    stats: { power: 18, stamina: 20, speed: 28, technique: 17 },
    sizeRangeCm: { min: 10, max: 24 },
    name: { th: 'ปลากระทุงเหวหมอกสนธยา', en: 'Duskmist Needlefish' },
    description: {
      th: 'ปลาปากเรียวยาวที่พุ่งผ่านผิวน้ำยามเย็นก่อนจะหายไปในหมอก',
      en: 'A slender, spear-snouted fish that darts across the dusk water before fading into mist.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank'],
    tier: 1,
    rarity: 'common',
    habitat: ['reed-fringe', 'shallow-edge'],
    activeTime: ['morning', 'evening'],
    preferredBaitIds: ['red-worm', 'shiny-spinner'],
    sellValue: 9,
    rewards: { money: 9, reputation: 1 },
    collection: {
      entry: { th: 'ลำตัวยาววาวเงินตัดกับหมอกม่วงยามสนธยา', en: 'Its silver body cuts a quick line through the violet dusk mist.' },
      silhouette: 'fish-silhouette-reed-perch',
    },
    weightFactor: 0.42,
  },
  {
    id: 'mud-carp',
    artwork: '/images/fish_art_a/Stonejaw Catfish_ Ancient River Guardians.png',
    behavior: 'steady',
    stats: { power: 25, stamina: 32, speed: 12, technique: 14 },
    sizeRangeCm: { min: 16, max: 38 },
    name: { th: 'ปลาดุกกรามศิลา', en: 'Stonejaw Catfish' },
    description: {
      th: 'ปลาดุกตัวหนาเกราะแข็ง ใช้หนวดหาอาหารตามพื้นคลอง',
      en: 'A heavy, armored catfish that noses along the canal bed with stone-hard jaws.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank'],
    tier: 1,
    rarity: 'common',
    habitat: ['mud-bottom', 'shallow-edge'],
    activeTime: ['day', 'evening'],
    preferredBaitIds: ['bread-crumbs', 'red-worm'],
    sellValue: 12,
    rewards: { money: 12, reputation: 2 },
    collection: {
      entry: { th: 'กรามแข็งและเกราะเป็นปุ่มช่วยให้มันคุ้ยพื้นหินได้โดยไม่ถอย', en: 'Its plated jaw and knobby armor let it nose through stony riverbeds.' },
      silhouette: 'fish-silhouette-mud-carp',
    },
    weightFactor: 1.08,
  },
  {
    id: 'silver-barb',
    artwork: '/images/fish_art_a/Wind-Ribbon Trout in Mountain Rapids.png',
    behavior: 'steady',
    stats: { power: 22, stamina: 24, speed: 20, technique: 19 },
    sizeRangeCm: { min: 12, max: 29 },
    name: { th: 'ปลาเทราต์แพรลม', en: 'Wind-Ribbon Trout' },
    description: {
      th: 'ปลาเทราต์สีเงินอมเขียวที่พริ้วว่ายต้านกระแสน้ำเชี่ยว',
      en: 'A pale trout with ribbon-like fins that holds its line in mountain rapids.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank', 'wooden-bridge'],
    tier: 1,
    rarity: 'common',
    habitat: ['slow-current', 'open-water'],
    activeTime: ['morning', 'day', 'evening'],
    preferredBaitIds: ['bread-crumbs', 'shiny-spinner'],
    sellValue: 11,
    rewards: { money: 11, reputation: 2 },
    collection: {
      entry: { th: 'ครีบยาวพลิ้วตามกระแสน้ำที่ไหลเร็วเหมือนริ้วลม', en: 'Long, windlike fins stream behind it as it rides the rapid current.' },
      silhouette: 'fish-silhouette-silver-barb',
    },
    weightFactor: 0.76,
  },
  {
    id: 'bluegill',
    artwork: '/images/fish_art_a/Lotus Bloom Arowana in a Magical Pond.png',
    behavior: 'ambush',
    stats: { power: 20, stamina: 22, speed: 19, technique: 27 },
    sizeRangeCm: { min: 9, max: 22 },
    name: { th: 'ปลามังกรบัว', en: 'Lotus Arowana' },
    description: {
      th: 'ปลาอะโรวาน่าเกล็ดเขียวมุก ลอยตัวสง่างามก่อนฉวยเหยื่อใกล้ใบบัว',
      en: 'A pearl-green arowana glides beneath the lotus blossoms before striking at prey.',
    },
    areaId: 'village-canal',
    spotIds: ['wooden-bridge', 'lotus-bed'],
    tier: 1,
    rarity: 'common',
    habitat: ['bridge-shadow', 'lotus-edge'],
    activeTime: ['day', 'evening'],
    preferredBaitIds: ['red-worm', 'lotus-grub'],
    sellValue: 10,
    rewards: { money: 10, reputation: 2 },
    collection: {
      entry: { th: 'ครีบยาวพริ้วไหวอย่างสุขุมก่อนพุ่งฉวยเหยื่อ', en: 'Its long fins drift calmly until it lunges for nearby prey.' },
      silhouette: 'fish-silhouette-bluegill',
    },
    weightFactor: 0.58,
  },
  {
    id: 'lotus-goby',
    artwork: '/images/fish_art_a/Lotus Pond Koi Companions.png',
    behavior: 'steady',
    stats: { power: 14, stamina: 19, speed: 11, technique: 16 },
    sizeRangeCm: { min: 7, max: 17 },
    name: { th: 'ปลาคาร์ปใบบัว', en: 'Lotus Koi' },
    description: {
      th: 'ฝูงปลาคาร์ปสีอ่อนวนเล่นอยู่ใต้ใบบัวอย่างสงบ',
      en: 'Pale koi companions circle playfully beneath the lotus leaves.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 1,
    rarity: 'common',
    habitat: ['lotus-roots', 'still-water'],
    activeTime: ['morning', 'evening'],
    preferredBaitIds: ['lotus-grub', 'red-worm'],
    sellValue: 7,
    rewards: { money: 7, reputation: 1 },
    collection: {
      entry: { th: 'ปลาคาร์ปตัวเล็กมักว่ายตามตัวใหญ่ใกล้รากบัว', en: 'Smaller koi tend to follow the larger fish around the lotus roots.' },
      silhouette: 'fish-silhouette-lotus-goby',
    },
    weightFactor: 0.26,
  },
  {
    id: 'glass-catfish',
    artwork: '/images/fish_art_a/Poisonous Eels in the Haunted Swamp.png',
    behavior: 'darting',
    stats: { power: 31, stamina: 34, speed: 39, technique: 33 },
    sizeRangeCm: { min: 18, max: 43 },
    name: { th: 'ปลาไหลพิษ', en: 'Poison Eel' },
    description: {
      th: 'ปลาไหลสีม่วงหนามพิษวูบว่ายผ่านเงามืดใต้สะพาน',
      en: 'A violet, spine-backed eel flashes through the shadowed channel.',
    },
    areaId: 'village-canal',
    spotIds: ['wooden-bridge'],
    tier: 2,
    rarity: 'uncommon',
    habitat: ['bridge-shadow', 'deep-channel'],
    activeTime: ['evening', 'night'],
    preferredBaitIds: ['red-worm', 'glow-moth'],
    sellValue: 32,
    rewards: { money: 32, reputation: 4 },
    collection: {
      entry: { th: 'หนามพิษเรืองแสงจาง ๆ เตือนนักตกปลาไม่ให้จับด้วยมือเปล่า', en: 'Its dimly glowing venom spines warn anglers not to handle it bare-handed.' },
      silhouette: 'fish-silhouette-glass-catfish',
    },
    weightFactor: 1.34,
  },
  {
    id: 'golden-carp',
    artwork: '/images/fish_art_a/Celestial Goldfish in a Sunlit Shrine Pond.png',
    behavior: 'steady',
    stats: { power: 39, stamina: 46, speed: 23, technique: 35 },
    sizeRangeCm: { min: 28, max: 62 },
    name: { th: 'ปลาทองสวรรค์', en: 'Celestial Goldfish' },
    description: {
      th: 'ปลาทองประกายเงินที่ว่ายวนอย่างสง่างามใต้ศาลาแสงตะวัน',
      en: 'A bright celestial goldfish with pale fins circles the sunlit shrine pool.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 2,
    rarity: 'uncommon',
    habitat: ['lotus-edge', 'mud-bottom'],
    activeTime: ['morning', 'day'],
    preferredBaitIds: ['bread-crumbs', 'lotus-grub'],
    sellValue: 48,
    rewards: { money: 48, reputation: 5 },
    collection: {
      entry: { th: 'ครีบสีอ่อนพริ้วไหวรอบเกล็ดทองเมื่อมันลอยผ่านแสงอุ่น', en: 'Pale fins fan around its gold scales as it drifts through warm light.' },
      silhouette: 'fish-silhouette-golden-carp',
    },
    weightFactor: 2.45,
  },
  {
    id: 'river-pike',
    artwork: '/images/fish_art_a/Armored Iron Gar in Ruined Waterways.png',
    behavior: 'ambush',
    stats: { power: 62, stamina: 56, speed: 28, technique: 47 },
    sizeRangeCm: { min: 32, max: 71 },
    name: { th: 'ปลาการ์เกราะเหล็ก', en: 'Armored Iron Gar' },
    description: {
      th: 'นักล่าปากยาวเกราะหนาซุ่มรอเหยื่อ ก่อนพุ่งทะลวงด้วยแรงมหาศาล',
      en: 'An armored, long-snouted hunter that waits in cover, then surges with heavy force.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 2,
    rarity: 'uncommon',
    habitat: ['lotus-cover', 'deep-channel'],
    activeTime: ['morning', 'evening'],
    preferredBaitIds: ['shiny-spinner', 'red-worm'],
    sellValue: 56,
    rewards: { money: 56, reputation: 6 },
    collection: {
      entry: { th: 'แผ่นเกราะหนาและปากยาวบอกถึงแรงพุ่งของมัน อย่าฝืนสายเมื่อมันเร่งหนี', en: 'Its plated hide and long snout hint at its power; brace when it surges.' },
      silhouette: 'fish-silhouette-river-pike',
    },
    weightFactor: 2.92,
    combat: { archetype: 'bruiser', resistance: 64 },
  },
  {
    id: 'lantern-catfish',
    artwork: '/images/fish_art_a/Emberfangs of the Molten River.png',
    behavior: 'ambush',
    stats: { power: 56, stamina: 62, speed: 31, technique: 54 },
    sizeRangeCm: { min: 39, max: 86 },
    name: { th: 'ปลาเขี้ยวเพลิง', en: 'Emberfang' },
    description: {
      th: 'ปลานักล่าสีแดงเพลิงเขี้ยวแหลมที่ซุ่มโจมตีในน้ำอุ่น',
      en: 'A broad, ember-scaled predator with sharp teeth that ambushes in warm water.',
    },
    areaId: 'village-canal',
    spotIds: ['wooden-bridge'],
    tier: 3,
    rarity: 'rare',
    habitat: ['bridge-shadow', 'deep-channel'],
    activeTime: ['night'],
    preferredBaitIds: ['red-worm', 'glow-moth'],
    sellValue: 105,
    rewards: { money: 105, reputation: 10 },
    collection: {
      entry: { th: 'เขี้ยวและครีบสีเพลิงแสดงให้เห็นว่ามันพร้อมพุ่งงับเหยื่อ', en: 'Its fiery fins and teeth signal a hunter built for sudden strikes.' },
      silhouette: 'fish-silhouette-lantern-catfish',
    },
    weightFactor: 4.72,
  },
  {
    id: 'moon-koi',
    artwork: '/images/fish_art_a/Majestic Ice Koi in a Crystal Temple Pond.png',
    behavior: 'darting',
    stats: { power: 62, stamina: 69, speed: 58, technique: 64 },
    sizeRangeCm: { min: 44, max: 91 },
    name: { th: 'ปลาคาร์ปน้ำแข็งผลึก', en: 'Crystal Ice Koi' },
    description: {
      th: 'ปลาคาร์ปสีฟ้าขาวระยิบระยับ เคลื่อนไหวรวดเร็วในสายน้ำใสเย็น',
      en: 'A pearl-blue koi that bursts through the cold, crystalline water.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 3,
    rarity: 'rare',
    habitat: ['lotus-edge', 'still-water'],
    activeTime: ['night'],
    preferredBaitIds: ['lotus-grub', 'glow-moth'],
    sellValue: 132,
    rewards: { money: 132, reputation: 12 },
    collection: {
      entry: { th: 'ลวดลายสีฟ้าขาวแตกประกายเหมือนน้ำแข็งเมื่อมันเร่งว่าย', en: 'Its pale blue markings shimmer like ice whenever it darts away.' },
      silhouette: 'fish-silhouette-moon-koi',
    },
    weightFactor: 5.36,
  },
  {
    id: 'old-river-king',
    artwork: '/images/fish_art_a/Moonlit Shadow Snakeheads.png',
    behavior: 'king',
    stats: { power: 96, stamina: 100, speed: 68, technique: 92 },
    sizeRangeCm: { min: 118, max: 186 },
    name: { th: 'พญาช่อนเงาจันทร์', en: 'Moon Shadow Snakehead' },
    description: {
      th: 'พญาช่อนเงาจันทร์เปิดฉากด้วยการดึงเป็นจังหวะ ก่อนเข้าสู่ช่วงคลั่งกลางศึกและเร่งหนีเมื่อแรงใกล้หมด',
      en: 'The Moon Shadow Snakehead begins with measured pulls, surges into a mid-fight frenzy, then makes a desperate distance run when exhausted.',
    },
    areaId: 'village-canal',
    spotIds: ['deep-pool'],
    tier: 4,
    rarity: 'king',
    habitat: ['deep-pool', 'submerged-root'],
    activeTime: ['evening', 'night'],
    preferredBaitIds: ['glow-moth', 'shiny-spinner'],
    sellValue: 420,
    rewards: { money: 420, reputation: 40 },
    collection: {
      entry: { th: 'ครีบมืดดูลึกลับใต้แสงจันทร์และเปลี่ยนจังหวะการต่อสู้ถึงสามระยะ', en: 'Dark fins ghost beneath moonlight as the King Fish changes rhythm through three phases.' },
      silhouette: 'fish-silhouette-old-river-king',
    },
    weightFactor: 14.8,
    combat: {
      archetype: 'berserker',
      resistance: 92,
      bossPhases: { frenzyAt: 0.6, desperateAt: 0.25 },
    },
  },
] satisfies FishDefinition[];
