import type { FishDefinition } from './types';

export const FISH = [
  {
    id: 'river-minnow',
    behavior: 'darting',
    stats: { power: 10, stamina: 12, speed: 34, technique: 9 },
    sizeRangeCm: { min: 4, max: 11 },
    name: { th: 'ปลาซิวสายธาร', en: 'River Minnow' },
    description: {
      th: 'ปลาตัวจิ๋วว่องไวที่ว่ายรวมฝูงใกล้ริมตลิ่ง',
      en: 'A tiny, quick fish that schools along the quiet canal edge.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank'],
    tier: 1,
    rarity: 'common',
    habitat: ['shallow-edge', 'open-water'],
    activeTime: ['morning', 'day'],
    preferredBaitIds: ['bread-crumbs', 'shiny-spinner'],
    sellValue: 4,
    rewards: { money: 4, reputation: 1 },
    collection: {
      entry: { th: 'ฝูงปลาซิวทำให้ผิวน้ำเป็นประกายระยิบระยับ', en: 'A school of minnows can make the water sparkle in the morning light.' },
      silhouette: 'fish-silhouette-river-minnow',
    },
    weightFactor: 0.08,
    combat: { archetype: 'calm', resistance: 14 },
  },
  {
    id: 'reed-perch',
    behavior: 'darting',
    stats: { power: 18, stamina: 20, speed: 28, technique: 17 },
    sizeRangeCm: { min: 10, max: 24 },
    name: { th: 'ปลากะพงกออ้อ', en: 'Reed Perch' },
    description: {
      th: 'นักล่าตัวเล็กที่พุ่งออกจากกออ้อเมื่อเหยื่อเข้าใกล้',
      en: 'A small hunter that darts from the reeds when bait passes nearby.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank'],
    tier: 1,
    rarity: 'common',
    habitat: ['reed-fringe', 'shallow-edge'],
    activeTime: ['morning', 'evening'],
    preferredBaitIds: ['red-worm', 'shiny-spinner'],
    sellValue: 9,
    rewards: { money: 9, reputation: 1 },
    collection: {
      entry: { th: 'ปลาชนิดนี้ว่องไวเป็นพิเศษเมื่อซ่อนตัวในกออ้อ', en: 'Its speed makes the reed fringe a perfect hiding place.' },
      silhouette: 'fish-silhouette-reed-perch',
    },
    weightFactor: 0.42,
  },
  {
    id: 'mud-carp',
    behavior: 'steady',
    stats: { power: 25, stamina: 32, speed: 12, technique: 14 },
    sizeRangeCm: { min: 16, max: 38 },
    name: { th: 'ปลาตะเพียนโคลน', en: 'Mud Carp' },
    description: {
      th: 'ปลาตัวแน่นที่คุ้ยหาอาหารตามพื้นโคลนอย่างใจเย็น',
      en: 'A sturdy bottom-feeder that searches the silt with patient determination.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank'],
    tier: 1,
    rarity: 'common',
    habitat: ['mud-bottom', 'shallow-edge'],
    activeTime: ['day', 'evening'],
    preferredBaitIds: ['bread-crumbs', 'red-worm'],
    sellValue: 12,
    rewards: { money: 12, reputation: 2 },
    collection: {
      entry: { th: 'มันไม่รีบร้อนและมักใช้แรงดึงยาว ๆ ตอนติดเบ็ด', en: 'It rarely rushes, but leans into a long, steady pull once hooked.' },
      silhouette: 'fish-silhouette-mud-carp',
    },
    weightFactor: 1.08,
  },
  {
    id: 'silver-barb',
    behavior: 'steady',
    stats: { power: 22, stamina: 24, speed: 20, technique: 19 },
    sizeRangeCm: { min: 12, max: 29 },
    name: { th: 'ปลาตะเพียนเงิน', en: 'Silver Barb' },
    description: {
      th: 'ปลาสีเงินที่ว่ายตัดกระแสน้ำรอบเสาสะพานและริมตลิ่ง',
      en: 'A bright-scaled canal regular that cruises against the current near bridge posts.',
    },
    areaId: 'village-canal',
    spotIds: ['shallow-bank', 'wooden-bridge'],
    tier: 1,
    rarity: 'common',
    habitat: ['slow-current', 'open-water'],
    activeTime: ['morning', 'day', 'evening'],
    preferredBaitIds: ['bread-crumbs', 'shiny-spinner'],
    sellValue: 11,
    rewards: { money: 11, reputation: 2 },
    collection: {
      entry: { th: 'เกล็ดของมันสะท้อนแสงเป็นริ้วเงินเมื่อลอยขึ้นใกล้ผิวน้ำ', en: 'Its scales flash silver as it turns near the surface.' },
      silhouette: 'fish-silhouette-silver-barb',
    },
    weightFactor: 0.76,
  },
  {
    id: 'bluegill',
    behavior: 'ambush',
    stats: { power: 20, stamina: 22, speed: 19, technique: 27 },
    sizeRangeCm: { min: 9, max: 22 },
    name: { th: 'ปลากระดี่ฟ้า', en: 'Bluegill' },
    description: {
      th: 'ปลาลายฟ้าที่ชอบพุ่งงับเหยื่อจากเงาใต้น้ำ',
      en: 'A blue-striped fish that snaps at bait from the bridge shadows.',
    },
    areaId: 'village-canal',
    spotIds: ['wooden-bridge', 'lotus-bed'],
    tier: 1,
    rarity: 'common',
    habitat: ['bridge-shadow', 'lotus-edge'],
    activeTime: ['day', 'evening'],
    preferredBaitIds: ['red-worm', 'lotus-grub'],
    sellValue: 10,
    rewards: { money: 10, reputation: 2 },
    collection: {
      entry: { th: 'มันซ่อนตัวเงียบ ๆ ก่อนฉวยโอกาสในเสี้ยววินาที', en: 'It waits quietly, then takes its chance in a sudden snap.' },
      silhouette: 'fish-silhouette-bluegill',
    },
    weightFactor: 0.58,
  },
  {
    id: 'lotus-goby',
    behavior: 'steady',
    stats: { power: 14, stamina: 19, speed: 11, technique: 16 },
    sizeRangeCm: { min: 7, max: 17 },
    name: { th: 'ปลาบู่ใบบัว', en: 'Lotus Goby' },
    description: {
      th: 'ปลาบู่ตัวเล็กที่เกาะอยู่ตามรากบัวและขอบกอใบบัว',
      en: 'A little canal goby that lingers around lotus roots and the edge of the bed.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 1,
    rarity: 'common',
    habitat: ['lotus-roots', 'still-water'],
    activeTime: ['morning', 'evening'],
    preferredBaitIds: ['lotus-grub', 'red-worm'],
    sellValue: 7,
    rewards: { money: 7, reputation: 1 },
    collection: {
      entry: { th: 'มันซุกตัวอยู่ใกล้รากบัวและเคลื่อนไหวไม่ไกลจากแหล่งอาหาร', en: 'It stays close to the lotus roots where small morsels collect.' },
      silhouette: 'fish-silhouette-lotus-goby',
    },
    weightFactor: 0.26,
  },
  {
    id: 'glass-catfish',
    behavior: 'darting',
    stats: { power: 31, stamina: 34, speed: 39, technique: 33 },
    sizeRangeCm: { min: 18, max: 43 },
    name: { th: 'ปลาดุกแก้ว', en: 'Glass Catfish' },
    description: {
      th: 'ปลาหนวดใสที่วูบหายไปกับเงาสะท้อนใต้สะพาน',
      en: 'A translucent whiskered fish that vanishes into reflections beneath the bridge.',
    },
    areaId: 'village-canal',
    spotIds: ['wooden-bridge'],
    tier: 2,
    rarity: 'uncommon',
    habitat: ['bridge-shadow', 'deep-channel'],
    activeTime: ['evening', 'night'],
    preferredBaitIds: ['red-worm', 'glow-moth'],
    sellValue: 32,
    rewards: { money: 32, reputation: 4 },
    collection: {
      entry: { th: 'ลำตัวโปร่งแสงทำให้มองเห็นแสงลอดผ่านระหว่างว่ายน้ำ', en: 'Light seems to pass through its body as it slips through the dark water.' },
      silhouette: 'fish-silhouette-glass-catfish',
    },
    weightFactor: 1.34,
  },
  {
    id: 'golden-carp',
    behavior: 'steady',
    stats: { power: 39, stamina: 46, speed: 23, technique: 35 },
    sizeRangeCm: { min: 28, max: 62 },
    name: { th: 'ปลาคาร์ปทอง', en: 'Golden Carp' },
    description: {
      th: 'ปลาคาร์ปเกล็ดสีทองที่วนหาอาหารอยู่รอบกอบัว',
      en: 'A gold-scaled carp that circles the lotus bed in search of a generous meal.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 2,
    rarity: 'uncommon',
    habitat: ['lotus-edge', 'mud-bottom'],
    activeTime: ['morning', 'day'],
    preferredBaitIds: ['bread-crumbs', 'lotus-grub'],
    sellValue: 48,
    rewards: { money: 48, reputation: 5 },
    collection: {
      entry: { th: 'สีทองของมันจะเด่นชัดเมื่อว่ายผ่านช่องว่างของใบบัว', en: 'Its golden scales stand out whenever it passes between the lotus leaves.' },
      silhouette: 'fish-silhouette-golden-carp',
    },
    weightFactor: 2.45,
  },
  {
    id: 'river-pike',
    behavior: 'ambush',
    stats: { power: 48, stamina: 39, speed: 44, technique: 47 },
    sizeRangeCm: { min: 32, max: 71 },
    name: { th: 'ปลาหอกคลอง', en: 'Canal Pike' },
    description: {
      th: 'นักล่าปากแหลมที่ซุ่มรอปลาตัวเล็กผ่านช่องใบบัว',
      en: 'A sharp-mouthed hunter that waits among the lotus leaves for smaller fish.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 2,
    rarity: 'uncommon',
    habitat: ['lotus-cover', 'deep-channel'],
    activeTime: ['morning', 'evening'],
    preferredBaitIds: ['shiny-spinner', 'red-worm'],
    sellValue: 56,
    rewards: { money: 56, reputation: 6 },
    collection: {
      entry: { th: 'มันพุ่งเข้าใส่เหยื่ออย่างฉับพลันแล้วพยายามกลับไปซ่อน', en: 'It strikes without warning and tries to retreat to cover.' },
      silhouette: 'fish-silhouette-river-pike',
    },
    weightFactor: 2.92,
    combat: { archetype: 'sprinter', resistance: 46 },
  },
  {
    id: 'lantern-catfish',
    behavior: 'ambush',
    stats: { power: 56, stamina: 62, speed: 31, technique: 54 },
    sizeRangeCm: { min: 39, max: 86 },
    name: { th: 'ปลาดุกโคม', en: 'Lantern Catfish' },
    description: {
      th: 'ปลาหนวดใหญ่ที่มีจุดเรืองแสงจาง ๆ และออกหากินยามค่ำ',
      en: 'A broad whiskered hunter with faint glowing spots that emerge after dusk.',
    },
    areaId: 'village-canal',
    spotIds: ['wooden-bridge'],
    tier: 3,
    rarity: 'rare',
    habitat: ['bridge-shadow', 'deep-channel'],
    activeTime: ['night'],
    preferredBaitIds: ['red-worm', 'glow-moth'],
    sellValue: 105,
    rewards: { money: 105, reputation: 10 },
    collection: {
      entry: { th: 'จุดแสงบนหนวดช่วยให้มันตามหาอาหารในเงามืด', en: 'Faint lights along its whiskers guide it through the shadowed channel.' },
      silhouette: 'fish-silhouette-lantern-catfish',
    },
    weightFactor: 4.72,
  },
  {
    id: 'moon-koi',
    behavior: 'darting',
    stats: { power: 62, stamina: 69, speed: 58, technique: 64 },
    sizeRangeCm: { min: 44, max: 91 },
    name: { th: 'ปลาคาร์ปจันทร์', en: 'Moon Koi' },
    description: {
      th: 'ปลาสีมุกที่ปรากฏเหนือกอบัวในคืนฟ้าโปร่ง',
      en: 'A pearl-colored koi that appears above the lotus bed on clear nights.',
    },
    areaId: 'village-canal',
    spotIds: ['lotus-bed'],
    tier: 3,
    rarity: 'rare',
    habitat: ['lotus-edge', 'still-water'],
    activeTime: ['night'],
    preferredBaitIds: ['lotus-grub', 'glow-moth'],
    sellValue: 132,
    rewards: { money: 132, reputation: 12 },
    collection: {
      entry: { th: 'ลวดลายสีมุกสะท้อนแสงจันทร์ขณะมันพุ่งหนีอย่างรวดเร็ว', en: 'Its pearly markings catch moonlight as it darts away in a sudden burst.' },
      silhouette: 'fish-silhouette-moon-koi',
    },
    weightFactor: 5.36,
  },
  {
    id: 'old-river-king',
    behavior: 'king',
    stats: { power: 96, stamina: 100, speed: 68, technique: 92 },
    sizeRangeCm: { min: 118, max: 186 },
    name: { th: 'ราชาปลาเฒ่า', en: 'Old River King' },
    description: {
      th: 'ราชาปลาเพียงหนึ่งเดียวในแอ่งลึก ใช้แรงต้านเป็นจังหวะ สะบัดตัวเปลี่ยนทิศ และพุ่งหนีเป็นชุดอย่างคาดเดายาก',
      en: 'The canal’s sole King Fish: it alternates crushing holds, sudden direction changes, and chained surges that demand careful timing.',
    },
    areaId: 'village-canal',
    spotIds: ['deep-pool'],
    tier: 4,
    rarity: 'king',
    habitat: ['deep-pool', 'submerged-root'],
    activeTime: ['evening', 'night'],
    preferredBaitIds: ['glow-moth', 'shiny-spinner'],
    sellValue: 420,
    rewards: { money: 420, reputation: 40 },
    collection: {
      entry: { th: 'การต่อสู้กับราชาปลาเป็นบททดสอบสุดท้ายของคลองหมู่บ้าน', en: 'Facing the King Fish is the final test of the Village Canal chapter.' },
      silhouette: 'fish-silhouette-old-river-king',
    },
    weightFactor: 14.8,
    combat: { archetype: 'berserker', resistance: 96 },
  },
] satisfies FishDefinition[];
