import type { GearDefinition } from './types';

export const GEAR = [
  {
    id: 'reed-rod',
    category: 'rod',
    name: { th: 'คันเบ็ดกออ้อ', en: 'Reed Rod' },
    description: { th: 'คันเบาและควบคุมง่าย เหมาะกับการฝึก แต่รับแรงปลาตัวใหญ่ได้น้อย', en: 'Light and easy to control for practice, but it gives up leverage against large fish.' },
    tier: 1,
    rarity: 'common',
    price: 0,
    effects: { power: 1, control: 3, skillPower: 1 },
  },
  {
    id: 'hand-reel',
    category: 'reel',
    name: { th: 'รอกมือหมุน', en: 'Hand Reel' },
    description: { th: 'รอกพื้นฐานที่จับจังหวะได้ง่าย แต่เก็บสายช้า', en: 'A simple reel that is easy to manage, at the cost of slower line recovery.' },
    tier: 1,
    rarity: 'common',
    price: 0,
    effects: { control: 2, reelSpeed: -1 },
  },
  {
    id: 'fine-cotton-line',
    category: 'line',
    name: { th: 'สายฝ้ายเส้นเล็ก', en: 'Fine Cotton Line' },
    description: { th: 'สายบางช่วยควบคุมละเอียด แต่ขาดง่ายเมื่อรับแรงมาก', en: 'A fine line offers precise control but snaps more readily under heavy strain.' },
    tier: 1,
    rarity: 'common',
    price: 0,
    effects: { control: 3, lineStrength: -2 },
  },
  {
    id: 'barbless-hook',
    category: 'hook',
    name: { th: 'เบ็ดไร้เงี่ยง', en: 'Barbless Hook' },
    description: { th: 'เกี่ยวอย่างนุ่มนวลและช่วยให้ใช้ทักษะได้แม่น แต่ยึดปลาไม่แน่นเท่าเบ็ดหนาม', en: 'A gentle hook that rewards precise technique, but holds less firmly than a barbed one.' },
    tier: 1,
    rarity: 'common',
    price: 0,
    effects: { control: 2, skillPower: 2, power: -1 },
  },
  {
    id: 'bread-crumbs',
    category: 'bait',
    name: { th: 'เศษขนมปัง', en: 'Bread Crumbs' },
    description: { th: 'เหยื่อเริ่มต้นเรียบง่าย ดึงดูดปลากินพืชและปลาที่หากินตามพื้น', en: 'A simple starter bait for plant-eaters and fish that feed near the bottom.' },
    tier: 1,
    rarity: 'common',
    price: 0,
    effects: { attraction: 2 },
    baitTargets: ['river-minnow', 'mud-carp', 'silver-barb', 'golden-carp'],
  },
  {
    id: 'willow-rod',
    category: 'rod',
    name: { th: 'คันเบ็ดไม้หลิว', en: 'Willow Rod' },
    description: { th: 'คันสมดุลที่เพิ่มแรงส่งเล็กน้อยโดยไม่เสียการควบคุมมาก', en: 'A balanced starter rod with a little more force and only a small control trade-off.' },
    tier: 1,
    rarity: 'common',
    price: 42,
    effects: { power: 3, control: 1, attraction: 1 },
  },
  {
    id: 'canal-caster',
    category: 'rod',
    name: { th: 'คันตีคลอง', en: 'Canal Caster' },
    description: { th: 'ส่งเหยื่อได้ไกลและเพิ่มแรงงัด แต่คุมจังหวะยากขึ้น', en: 'Casts farther and adds leverage, though delicate timing takes more care.' },
    tier: 2,
    rarity: 'uncommon',
    price: 118,
    effects: { power: 5, control: -1, reelSpeed: 1 },
    unlockAfter: 'first-catch',
  },
  {
    id: 'ferryman-rod',
    category: 'rod',
    name: { th: 'คันเรือข้ามฟาก', en: 'Ferryman Rod' },
    description: { th: 'คันแข็งสำหรับปลาตัวหนัก มีแรงมากแต่ไวต่อความผิดพลาด', en: 'A stout rod for heavy fish; powerful, but mistakes are less forgiving.' },
    tier: 3,
    rarity: 'rare',
    price: 245,
    effects: { power: 8, control: -3, skillPower: 2 },
    unlockAfter: 'king-hunt-unlocked',
  },
  {
    id: 'smooth-reel',
    category: 'reel',
    name: { th: 'รอกลื่นไหล', en: 'Smooth Reel' },
    description: { th: 'หมุนเก็บสายได้ไวและนุ่มนวล แต่ไม่ได้ช่วยเพิ่มแรงดึง', en: 'Recovers line quickly and smoothly without adding much pulling force.' },
    tier: 1,
    rarity: 'common',
    price: 58,
    effects: { reelSpeed: 3, control: 1, power: -1 },
  },
  {
    id: 'power-reel',
    category: 'reel',
    name: { th: 'รอกแรงดึง', en: 'Power Reel' },
    description: { th: 'เฟืองแข็งแรงช่วยรับแรงและดึงกลับเร็ว แต่หมุนไม่คล่องเท่ารอกเบา', en: 'Strong gearing helps hold and recover line, though its heavier turn is less forgiving.' },
    tier: 2,
    rarity: 'uncommon',
    price: 136,
    effects: { lineStrength: 2, reelSpeed: 2, control: -1 },
    unlockAfter: 'old-fisher-rumor',
  },
  {
    id: 'canal-braid',
    category: 'line',
    name: { th: 'สายถักคลอง', en: 'Canal Braid' },
    description: { th: 'สายถักรับแรงดีขึ้น แลกกับการเคลื่อนไหวที่หนืดขึ้นเล็กน้อย', en: 'Braided fibers withstand more strain, with a small penalty to nimble handling.' },
    tier: 1,
    rarity: 'common',
    price: 64,
    effects: { lineStrength: 4, control: 1, reelSpeed: -1 },
  },
  {
    id: 'tough-moon-line',
    category: 'line',
    name: { th: 'สายเหนียวแสงจันทร์', en: 'Moon-Tough Line' },
    description: { th: 'สายหนาพิเศษรับแรงปลาหนักได้มาก แต่ควบคุมปลาตัวเล็กลำบาก', en: 'A thick, strong line for heavy fish, though small catches are harder to guide.' },
    tier: 2,
    rarity: 'uncommon',
    price: 142,
    effects: { lineStrength: 7, control: -2 },
    unlockAfter: 'king-hunt-unlocked',
  },
  {
    id: 'wide-gap-hook',
    category: 'hook',
    name: { th: 'เบ็ดกว้าง', en: 'Wide-Gap Hook' },
    description: { th: 'ช่องเบ็ดกว้างเกี่ยวปลาตัวใหญ่ได้ดี แต่เสียความละเอียดกับปลาตัวเล็ก', en: 'Its wide gap suits larger fish, but sacrifices finesse on small catches.' },
    tier: 1,
    rarity: 'common',
    price: 46,
    effects: { power: 3, lineStrength: 1, control: -1 },
  },
  {
    id: 'needle-hook',
    category: 'hook',
    name: { th: 'เบ็ดเข็ม', en: 'Needle Hook' },
    description: { th: 'ปลายแหลมช่วยให้เกี่ยวเร็ว แต่ต้องคุมสายไม่ให้ตึงเกินไป', en: 'A sharp point helps set quickly, but demands care to avoid over-tightening the line.' },
    tier: 2,
    rarity: 'uncommon',
    price: 92,
    effects: { attraction: 1, power: 2, control: -2, reelSpeed: 1 },
    unlockAfter: 'first-catch',
  },
  {
    id: 'red-worm',
    category: 'bait',
    name: { th: 'ไส้เดือนแดง', en: 'Red Worm' },
    description: { th: 'เหยื่อสดสารพัดประโยชน์ที่ปลาหนวดและนักล่าตัวเล็กชอบ', en: 'A lively all-purpose bait favored by whiskered fish and smaller hunters.' },
    tier: 1,
    rarity: 'common',
    price: 12,
    effects: { attraction: 3, control: 1 },
    baitTargets: ['reed-perch', 'mud-carp', 'bluegill', 'lotus-goby', 'glass-catfish', 'river-pike', 'lantern-catfish'],
  },
  {
    id: 'lotus-grub',
    category: 'bait',
    name: { th: 'หนอนบัว', en: 'Lotus Grub' },
    description: { th: 'หนอนตัวอวบจากกอบัวที่ดึงดูดปลาซึ่งวนเวียนตามราก', en: 'A plump grub from the lotus bed, especially tempting to fish near its roots.' },
    tier: 1,
    rarity: 'common',
    price: 18,
    effects: { attraction: 3, skillPower: 1 },
    baitTargets: ['bluegill', 'lotus-goby', 'golden-carp', 'moon-koi'],
  },
  {
    id: 'shiny-spinner',
    category: 'bait',
    name: { th: 'เหยื่อหมุนแวววาว', en: 'Shiny Spinner' },
    description: { th: 'เหยื่อโลหะสะท้อนแสง ล่อปลาว่องไวและนักล่าที่พุ่งฉวยเหยื่อ', en: 'A flashing metal lure that draws quick fish and hunters that strike on the move.' },
    tier: 1,
    rarity: 'common',
    price: 24,
    effects: { attraction: 4, reelSpeed: 1, control: -1 },
    baitTargets: ['river-minnow', 'reed-perch', 'silver-barb', 'river-pike', 'old-river-king'],
  },
  {
    id: 'glow-moth',
    category: 'bait',
    name: { th: 'แมลงเรืองแสง', en: 'Glow Moth' },
    description: { th: 'เหยื่อส่องแสงอ่อนสำหรับปลาที่ออกหากินในคลองยามค่ำ', en: 'A softly glowing lure for fish that stir in the canal after dark.' },
    tier: 2,
    rarity: 'uncommon',
    price: 52,
    effects: { attraction: 5, skillPower: 1, control: -1 },
    unlockAfter: 'old-fisher-rumor',
    baitTargets: ['glass-catfish', 'lantern-catfish', 'moon-koi', 'old-river-king'],
  },
] satisfies GearDefinition[];
